# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SumSingle <- function(modelList, testData) {
    .Call('_LMboost_SumSingle', PACKAGE = 'LMboost', modelList, testData)
}

VoteSingle <- function(modelList, testData) {
    .Call('_LMboost_VoteSingle', PACKAGE = 'LMboost', modelList, testData)
}

WeightedVotesSingle <- function(modelList, testData, Weights, totalweight) {
    .Call('_LMboost_WeightedVotesSingle', PACKAGE = 'LMboost', modelList, testData, Weights, totalweight)
}

